Feature: Add export of build metadata on contracts-ethers
aragon/osx pull request #431
Opened 2023-07-12 10:10 UTC by josemarinas

## Description

The SDK has no access to the build metadata on the contracts-ethers package, this PR adds the exports ins a similar way to the active contracts list so it has access

Task: [OS-486](https://aragonassociation.atlassian.net/browse/OS-486)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] I have made corresponding changes to the documentation.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have updated the `DEPLOYMENT_CHECKLIST` file in the root folder.
- [ ] I have updated the `UPDATE_CHECKLIST` file in the root folder.

2023-07-12 10:39 UTC, Rekard0 approved these changes

2023-07-12 11:21 UTC, Michael-A-Heuer reviewed
Is there a reason why we don't export the `release-metadata.json` files yet?

2023-07-12 11:32 UTC, Michael-A-Heuer commented
> Is there a reason why we don't export the `release-metadata.json` files yet?

After a short discussion with @Rekard0, the build-metadata and release-metadata can be fetched from subgraph.
The build-metadata can also be obtained directly from the contract with `getVersion()` (see https://goerli.etherscan.io/address/0x92C090cffC592B1bC321aCfAF735057B876375F8#readProxyContract#F8), e.g., with `[1,1]` for version 1.1.

2023-07-12 11:40 UTC, Rekard0 commented
@mathewmeconry what would be the best place for publishing these metadata?

currently they are accessible on Subgraph, but that mean SDK need to provide these functionalities via context and client and not in a static way,

2023-08-28 13:00 UTC, Michael-A-Heuer requested changes
Should this PR be closed @Rekard0 ?

2023-10-09 08:38 UTC, closed without merging

2023-10-09 08:39 UTC, Rekard0 commented
Closed since this data need to be read from the blockchain