OS-784 Bug: fix delegatee wrong deletion
aragon/osx pull request #488
Opened 2023-10-23 11:13 UTC by Rekard0

## Description

Please include a summary of the change and be sure you follow the contributions rules we do provide [here](./CONTRIBUTIONS.md)

Task ID: [OS-784](https://aragonassociation.atlassian.net/browse/OS-784)

## Type of change

See the framework lifecylce in `packages/contracts/docs/framework-lifecycle` to decide what kind of change this pull request is.

- [ ] Bug fix (non-breaking change which fixes an issue)
- [ ] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to not work as expected)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have updated the `DEPLOYMENT_CHECKLIST` file in the root folder.
- [ ] I have updated the `UPDATE_CHECKLIST` file in the root folder.

2023-10-23 16:56 UTC, Michael-A-Heuer commented on packages/subgraph/tests/helpers/method-classes.ts
> +    toDelegate: string = this.address.toHexString(),
Why was this changed?

2023-10-23 16:57 UTC, Michael-A-Heuer commented on packages/subgraph/tests/token/governance-erc20.test.ts
> +    // });
Please remove

2023-10-23 16:58 UTC, Michael-A-Heuer commented on packages/subgraph/tests/token/governance-erc20.test.ts
> +      /* member one has 100s token delegated to member two*/
```suggestion
      /* member one has 100 tokens delegated to member two*/
```

2023-10-23 17:03 UTC, Michael-A-Heuer requested changes
Minor comment. LGTM otherwise

2023-10-25 09:23 UTC, Rekard0 commented on packages/subgraph/tests/token/governance-erc20.test.ts
> +      /* member one has 100s token delegated to member two*/
addressed [e3b807e](https://github.com/aragon/osx/pull/488/commits/e3b807e09d8714ca2bb8110aa3fe9d323d454152)

2023-10-25 09:23 UTC, Rekard0 commented on packages/subgraph/tests/token/governance-erc20.test.ts
> +    // });
addressed at [e3b807e](https://github.com/aragon/osx/pull/488/commits/e3b807e09d8714ca2bb8110aa3fe9d323d454152)

2023-10-25 12:47 UTC, mathewmeconry approved these changes

2023-10-25 12:56 UTC, Michael-A-Heuer approved these changes

2023-10-25 13:50 UTC, merged