Create flow to update subgraph docs on Dev-Portal
aragon/osx pull request #557
Opened 2024-03-15 15:46 UTC by banasa44

## Description

This PR introduces everything needed to generate Subgraph documentation and send it to the Developer-Portal. It mimics the workflows on SDK and OSX/contracts.

It doesn't generate all the subraph documentation as the reference-guide documentation is generated in the Dev-Portal itself as we are using a plugin from Docusaurus that generates it. What we are providing though is the result of the introspection query needed to generate the subgraph docs.

The PR includes 2 query example samples as this will be the actual workflow, the test for these queries will be done in following-up tasks. 

Task ID: [OS-1051](https://aragonassociation.atlassian.net/browse/OS-1051)

## Type of change

- [x] New feature (non-breaking change which adds functionality)

## Checklist:

- [ ] I have selected the correct base branch.
- [ ] I have performed a self-review of my own code.
- [ ] I have commented my code, particularly in hard-to-understand areas.
- [ ] My changes generate no new warnings.
- [ ] Any dependent changes have been merged and published in downstream modules.
- [ ] I ran all tests with success and extended them if necessary.
- [ ] I have updated the `CHANGELOG.md` file in the root folder.
- [ ] I have updated the `DEPLOYMENT_CHECKLIST` file in the root folder.
- [ ] I have updated the `UPDATE_CHECKLIST` file in the root folder.

2024-03-25 12:15 UTC, Rekard0 commented on .gitignore
> +!packages/subgraph/docs/developer-portal/01-query-examples/index.md
```suggestion
!packages/subgraph/docs/developer-portal/01-query-examples/index.md

```

2024-03-25 14:14 UTC, Rekard0 commented on packages/subgraph/docs/codegen.yml
> +      - introspection
can we move this file to the root/ && update the package.json

2024-03-25 14:15 UTC, Rekard0 commented on .gitignore
> +!packages/subgraph/docs/developer-portal/01-query-examples/index.md
i think we should also ignore `schema-introspection.json`

2024-03-25 14:51 UTC, Rekard0 commented on packages/subgraph/src/examples/01-dao-query.ts
> +export const QueryDaos = gql`
```suggestion
`;

export const QueryDaos = gql`
```

2024-03-25 14:53 UTC, Rekard0 commented on packages/subgraph/package.json
> +    "generate:introspection": "cd docs && graphql-codegen && prettier schema-introspection.json --write",
once the .yml file is moved to root, this need to be updated

2024-03-26 15:25 UTC, Michael-A-Heuer requested changes
Let's make sure that the workflow does not run on closing a PR.
If this was found on the SDK, let's make sure to fix it there as well.

2024-03-26 16:33 UTC, banasa44 commented on .github/workflows/subgraph-documentation-update.yml
> +      - closed
makes perfect sense, didn't thought about manually closed PRs

2024-03-27 08:15 UTC, Michael-A-Heuer approved these changes

2024-04-02 12:56 UTC, Michael-A-Heuer approved these changes

2024-04-02 13:27 UTC, merged